name: GalaxyChatEmotes
version: 1.0.0
description: We've got the BEST emotes! THE BEST.
author: AKPWebDesign
website: https://github.com/PwnedGalaxy/GalaxyChatEmotes

main: net.pwnedgalaxy.bukkit.GalaxyChatEmotes.GalaxyChatEmotes

commands:
  shrug:
    aliases: [shruggie]
    description: ¯\_(ツ)_/¯
    usage: /shrug [message]
  lenny:
    description: ( ͡° ͜ʖ ͡°)
    usage: /lenny [message]
  disapprove:
    aliases: [disapproval, lod, lookofdisapproval]
    description: ಠ_ಠ
    usage: /disapprove [message]
  tableflip:
    aliases: [flip]
    description: (╯°□°）╯︵ ┻━┻
    usage: /tableflip [message]
  tablethrow:
    aliases: [throw]
    description: (ノಠ益ಠ)ノ彡┻━┻
    usage: /tablethrow [message]
  ohwell:
    aliases: [owell]
    description: ᕕ( ᐛ )ᕗ
    usage: /ohwell [message]
  kawaii:
    aliases: [かわいい]
    description: ｶﾜ(・∀・)ｲｲ!!
    usage: /kawaii [message]
